name: actions
on:
  push:
    branches: ["main"]
  pull_requets:
    branches: ["main"]

jobs:
  build_job:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run script
        - run: echo "Hello, World from Pavel"

        - name: Run second script
        - run: |
              echo "Add other actions",
              echo "Test, and deploy"
