name: actions

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  start_build_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Run script
          run: echo "Hello, World from Pavel"
          shell: bash
  end_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: End script
        run: echo "End script"
        shell: bash
